name: Build packages and publish automatic prerelease

on:
  push:
    branches: [ default ]
  pull_request:
    branches: [ default ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-debian-package:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
     
      - name: Build Debian package
        uses: cadadr/action-debian-package@master
        
      - name: Rename Debian package
        run: |
          mv pomodorino*_all.deb "pomodorino-$(git rev-parse --short HEAD)_all.deb"
        
      - name: Archive resulting package
        uses: actions/upload-artifact@v2
        with:
          name: debian-package
          path: pomodorino*.deb

  generate-release:
    runs-on: "ubuntu-latest"
    needs: build-debian-package

    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v2
        with:
          name: debian-package

      - uses: cadadr/action-automatic-releases@master
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development build"
          files: |
            pomodorino*.deb
