# This is a basic workflow to help you get started with Actions

name: Build debian package

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the default branch
  push:
    branches: [ default ]
  pull_request:
    branches: [ default ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: debian

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Build Debian package
        uses: dawidd6/action-debian-package@v1.3.2
        with:
          # Optional, relative to workspace directory
          source_directory: pomodorino
          # Optional, relative to workspace directory
          artifacts_directory: output

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
