# This is a basic workflow to help you get started with Actions

name: Build debian package

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the default branch
  push:
    branches: [ default ]
  pull_request:
    branches: [ default ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # From: https://stackoverflow.com/questions/10262754/set-debuild-dpkg-to-always-ignore-git-directories
      - name: hack .git away
        run: |
          cd pomodorino
          git archive master | tar -x -C ../pomodorino-archive
          cd ..
      
      - name: Build Debian package
        uses: dawidd6/action-debian-package@v1.3.2
        with:
          source_directory: pomodorino-archive
